### ISSUE TITLE
Removing Spoilery Words from WebPage

### ISSUE THREAD

**Issue by roryeiffe** [roryeiffe/Spoiler-Block#16]
The main goal of Spoiler Goal is to filter out words that could potentially spoil words on a webpage. The back-end code is written. We just need to connect it to the front-end so that it censors the webpage.

**Comment by roryeiffe** [comment]
Just to update this issue, on the branch "wordReplace", we have it working so that given a list of spoiler words, each block of text that contains a word with that spoiler is blocked out in red.

**Comment by Sushiman33** [comment]
Is this issue over? I am pretty sure this was done a while ago?
